name = "SocialBankRunsReplication"
uuid = "8b9c4d5e-1234-5678-9abc-def012345678"
authors = ["Robin Lenoir <lenoir.robin@gmail.com>"]
version = "1.0.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
DifferentialEquations = "7"
Interpolations = "0.14, 0.15"
LaTeXStrings = "1"
PGFPlotsX = "1"
Plots = "1"
julia = "1.9"
